### ISSUE TITLE
`code` is not always completely fixed-width?

### ISSUE THREAD

**Issue by stamourv** [racket/pict#11] opened 2015-12-03 20:45 UTC
When typesetting code that uses box-drawing characters, characters are not always aligned properly.
That seems to be the case only when actually coloring code (i.e., the are color changes involved); if I typeset things as strings, everything is aligned.

![screen shot 2015-12-03 at 2 38 37 pm](https://cloud.githubusercontent.com/assets/854429/11573540/79c25b02-99cc-11e5-9a68-293742b15a6d.png)

**Comment by rfindler** [comment] 2015-12-03 21:16
This is a problem of the fonts being used not a problem of the pict library.

**Comment by stamourv** [comment] 2015-12-03 21:42
Is it? Unless I'm mistaken, the two examples use the same font, but only one of them is aligned.

**Comment by rfindler** [comment] 2015-12-03 21:48
One is a serif font and the other is sans serif!!

**Comment by rfindler** [comment] 2015-12-03 21:49
Oh I see what you mean. IMO they are both not aligned. And the issue is the
fonts. It definitely doesn't belong as a discussion here!

**Comment by rfindler** [comment] 2015-12-08 17:41
I closed this prematurely. sorry.

**Comment by rfindler** [comment] 2015-12-09 20:05
Fixed by Vincent: https://github.com/racket/draw/commit/e90ae8bacc1173ba5696647c9fec2959a9ddbe16

**Closed by rfindler** 2015-12-09 20:05 UTC
