### ISSUE TITLE
Require and use of pict-convertible? in DrRacket evaluation window reports " access disallowed by code inspector"

### ISSUE THREAD

**Issue by dfeltey** [racket/pict#23] opened 2016-10-12 20:49 UTC
In DrRacket running 

```
Welcome to DrRacket, version 6.6.0.5--2016-06-15(-/f) [3m].
Language: racket, with debugging; memory limit: 1024 MB.
> (require pict/convert)
> pict-convertible?
```

Results in the error:

```
?: access disallowed by code inspector to unexported variable from module: "/Users/dan/racket/dev/racket/racket/share/pkgs/pict-lib/pict/private/pict.rkt" in: pict-convertible?
```

The same code, however, works correctly if entered in DrRacket's definitions window or run in the command line Racket repl.

**Comment by florence** [comment] 2016-10-13 03:29
A quick git bisect confirm this was the `pict-convert` changes. (b95113df1313b7eed6df1a0159dc8e8faddbc99f).

This commit made `pict/convert` depend on `pict/private/pict`, (which now provides `pict-convertible?` from a submodule), which seems relevant to the error message. I'm wondering if the sandboxing in DrRacket somehow doesn't like this?

**Comment by rfindler** [comment] 2016-11-18 15:09
This is, effectively, what DrRacket is doing:

```
#lang racket
(require pict)
(define orig-ns (current-namespace))
(parameterize ([current-code-inspector (make-inspector)])
  (parameterize ([current-namespace (make-base-namespace)])
    (namespace-attach-module orig-ns 'pict)
    (namespace-require 'racket/base)
    (eval '(require pict/convert))
    (eval 'pict-convertible?)))
```

And it raises that same error. 

As far as I can tell (and I could be missing something) from the code-inspector docs, this is the wrong result for that program.

**Comment by rfindler** [comment] 2016-11-18 15:11
(because the export of `pict-convertible?` isn't protected).

**Comment by mflatt** [comment] 2016-11-18 15:40
The implicit protection of an unexported (from its defining module) variable is working as intended here, but probably that intent needs to be refined.

The `pict-convertible?` function is defined in `pict/private/pict` and not exported, so it's marked as protected. The `convertible` submodule does export it, but re-exporting a protected binding doesn't make it unprotected. I'm not immediately sure which part of the rules should be changed to make this work.

Meanwhile, one workaround in this case would be to put the `pict-convertible?` definition in a submodule that exports `pict-convertible?`, and then the implicit protection doesn't kick in.

**Comment by rfindler** [comment] 2016-11-18 15:46
Ah, right. That does make sense to me. Thanks. (I can see why this example might suggest the rules should be changed, but also agree we don't need to do that for this issue.)

**Closed** 2016-11-18 16:13 UTC
